# Generated by Django 2.2 on 2020-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200821_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='contactpost',
            name='publish_date',
        ),
    ]
